// ATLProject1.idl : IDL source for ATLProject1
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLProject1.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(c86c36c2-30f5-48cc-9f66-141b1619a3da),
	version(1.0),
]
library ATLProject1Lib
{
	importlib("stdole2.tlb");
};

