// Copyright (c) Microsoft Corporation and Contributors
// Licensed under the MIT license.

namespace DevHome.QuietBackgroundProcesses
{
    [interface_name("IQuietBackgroundProcessesManager", e9bddf0b-291b-4657-9ddb-30ed15647145)]
    // [static_name("IActivationStatics", d44c89bd-f004-4bbc-8650-16bf3810c3d5)]
    //[default_interface]
    runtimeclass QuietBackgroundProcessesManager
    {
        static Int64 Start();
        static void Stop();
        static Boolean IsActive{ get; };
        static Int64 TimeLeftInSeconds{ get; };
        static UInt64 GetProcessCpuUsage2(UInt32 processId);
    }
}
