// Copyright (c) Microsoft Corporation and Contributors
// Licensed under the MIT license.

import "DevHome.QuietBackgroundProcesses.QuietBackgroundProcessesSession.idl";

namespace DevHome.QuietBackgroundProcesses
{
    [default_interface] runtimeclass QuietBackgroundProcessesSessionManager {
        static QuietBackgroundProcessesSession GetInstance();
        static QuietBackgroundProcessesSession CreateInstance();
    }
}
