// Copyright (c) Microsoft Corporation and Contributors
// Licensed under the MIT license.

// import "oaidl.idl";
// import "ocidl.idl";

[
    version(1.0),
    uuid(3221f13a-3c34-432e-b350-2336871de55a),
    helpstring("DevHomeQuietBackgroundProcessesElevatedServerRunningProbe 1.0 Type Library")
]
library DevHomeQuietBackgroundProcessesElevatedServerRunningProbeLibrary
{
    // importlib("stdole2.tlb");
    // importlib("stdole32.tlb");

    [
        version(1.0),
        uuid(33a0a1a0-b89c-44af-ba17-c828cea010c2),
        helpstring("DevHomeQuietBackgroundProcessesElevatedServerRunningProbe Class")
    ]
    coclass DevHomeQuietBackgroundProcessesElevatedServerRunningProbe
    {
        interface IUnknown;
    };
};
