// Copyright (c) Microsoft Corporation and Contributors
// Licensed under the MIT license.

namespace DevHome.QuietBackgroundProcesses
{
    [default_interface] runtimeclass QuietBackgroundProcessesSession
    {
        static QuietBackgroundProcessesSession GetSingleton();

        Int64 Start();
        void Stop();
        Boolean IsActive
        {
            get;
        };
        Int64 TimeLeftInSeconds
        {
            get;
        };
    }
}
