/* Header file automatically generated from DevHome.QuietBackgroundProcesses.QuietBackgroundProcessesSessionManager.idl */
/*
 * File built with Microsoft(R) MIDLRT Compiler Engine Version 10.00.0231 
 */

#pragma warning( disable: 4049 )  /* more than 64k source lines */

/* verify that the <rpcndr.h> version is high enough to compile this file*/
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 500
#endif

/* verify that the <rpcsal.h> version is high enough to compile this file*/
#ifndef __REQUIRED_RPCSAL_H_VERSION__
#define __REQUIRED_RPCSAL_H_VERSION__ 100
#endif

#include <rpc.h>
#include <rpcndr.h>

#ifndef __RPCNDR_H_VERSION__
#error this stub requires an updated version of <rpcndr.h>
#endif /* __RPCNDR_H_VERSION__ */

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif /*COM_NO_WINDOWS_H*/
#ifndef __DevHome2EQuietBackgroundProcesses2EQuietBackgroundProcessesSessionManager_h__
#define __DevHome2EQuietBackgroundProcesses2EQuietBackgroundProcessesSessionManager_h__
#ifndef __DevHome2EQuietBackgroundProcesses2EQuietBackgroundProcessesSessionManager_p_h__
#define __DevHome2EQuietBackgroundProcesses2EQuietBackgroundProcessesSessionManager_p_h__


#pragma once

// Ensure that the setting of the /ns_prefix command line switch is consistent for all headers.
// If you get an error from the compiler indicating "warning C4005: 'CHECK_NS_PREFIX_STATE': macro redefinition", this
// indicates that you have included two different headers with different settings for the /ns_prefix MIDL command line switch
#if !defined(DISABLE_NS_PREFIX_CHECKS)
#define CHECK_NS_PREFIX_STATE "always"
#endif // !defined(DISABLE_NS_PREFIX_CHECKS)


#pragma push_macro("MIDL_CONST_ID")
#undef MIDL_CONST_ID
#define MIDL_CONST_ID const __declspec(selectany)


// Header files for imported files
#include "inspectable.h"
#include "DevHome.QuietBackgroundProcesses.QuietBackgroundProcessesSession.h"

#if defined(__cplusplus) && !defined(CINTERFACE)
#if defined(__MIDL_USE_C_ENUM)
#define MIDL_ENUM enum
#else
#define MIDL_ENUM enum class
#endif
/* Forward Declarations */
#ifndef ____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_FWD_DEFINED__
#define ____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_FWD_DEFINED__
namespace ABI {
    namespace DevHome {
        namespace QuietBackgroundProcesses {
            interface IQuietBackgroundProcessesSessionManager;
        } /* QuietBackgroundProcesses */
    } /* DevHome */
} /* ABI */
#define __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager ABI::DevHome::QuietBackgroundProcesses::IQuietBackgroundProcessesSessionManager

#endif // ____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_FWD_DEFINED__

#ifndef ____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_FWD_DEFINED__
#define ____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_FWD_DEFINED__
namespace ABI {
    namespace DevHome {
        namespace QuietBackgroundProcesses {
            interface IQuietBackgroundProcessesSessionManagerStatics;
        } /* QuietBackgroundProcesses */
    } /* DevHome */
} /* ABI */
#define __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics ABI::DevHome::QuietBackgroundProcesses::IQuietBackgroundProcessesSessionManagerStatics

#endif // ____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_FWD_DEFINED__


namespace ABI {
    namespace DevHome {
        namespace QuietBackgroundProcesses {
            class QuietBackgroundProcessesSessionManager;
        } /* QuietBackgroundProcesses */
    } /* DevHome */
} /* ABI */



/*
 *
 * Interface DevHome.QuietBackgroundProcesses.IQuietBackgroundProcessesSessionManager
 *
 * Interface is a part of the implementation of type DevHome.QuietBackgroundProcesses.QuietBackgroundProcessesSessionManager
 *
 *
 * The IID for this interface was automatically generated by MIDLRT.
 *
 * Interface IID generation seed: DevHome.QuietBackgroundProcesses.IQuietBackgroundProcessesSessionManager:HRESULT GetInt(Int32*);
 *
 *
 */
#if !defined(____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_INTERFACE_DEFINED__)
#define ____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_INTERFACE_DEFINED__
extern const __declspec(selectany) _Null_terminated_ WCHAR InterfaceName_DevHome_QuietBackgroundProcesses_IQuietBackgroundProcessesSessionManager[] = L"DevHome.QuietBackgroundProcesses.IQuietBackgroundProcessesSessionManager";
namespace ABI {
    namespace DevHome {
        namespace QuietBackgroundProcesses {
            /* [uuid("812326e8-ebbc-5b6b-8a72-8840931e547a"), version, object, exclusiveto] */
            MIDL_INTERFACE("812326e8-ebbc-5b6b-8a72-8840931e547a")
            IQuietBackgroundProcessesSessionManager : public IInspectable
            {
            public:
                virtual HRESULT STDMETHODCALLTYPE GetInt(
                    /* [out, retval] */int * result
                    ) = 0;
                
            };

            MIDL_CONST_ID IID & IID_IQuietBackgroundProcessesSessionManager=_uuidof(IQuietBackgroundProcessesSessionManager);
            
        } /* QuietBackgroundProcesses */
    } /* DevHome */
} /* ABI */

EXTERN_C const IID IID___x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager;
#endif /* !defined(____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_INTERFACE_DEFINED__) */


/*
 *
 * Interface DevHome.QuietBackgroundProcesses.IQuietBackgroundProcessesSessionManagerStatics
 *
 * Interface is a part of the implementation of type DevHome.QuietBackgroundProcesses.QuietBackgroundProcessesSessionManager
 *
 *
 * The IID for this interface was automatically generated by MIDLRT.
 *
 * Interface IID generation seed: DevHome.QuietBackgroundProcesses.IQuietBackgroundProcessesSessionManagerStatics:HRESULT GetSession(DevHome.QuietBackgroundProcesses.QuietBackgroundProcessesSession**);HRESULT TryGetSession(DevHome.QuietBackgroundProcesses.QuietBackgroundProcessesSession**);
 *
 *
 */
#if !defined(____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_INTERFACE_DEFINED__)
#define ____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_INTERFACE_DEFINED__
extern const __declspec(selectany) _Null_terminated_ WCHAR InterfaceName_DevHome_QuietBackgroundProcesses_IQuietBackgroundProcessesSessionManagerStatics[] = L"DevHome.QuietBackgroundProcesses.IQuietBackgroundProcessesSessionManagerStatics";
namespace ABI {
    namespace DevHome {
        namespace QuietBackgroundProcesses {
            /* [uuid("e2335bd1-511c-572e-b204-e35b0878a9c7"), version, object, exclusiveto] */
            MIDL_INTERFACE("e2335bd1-511c-572e-b204-e35b0878a9c7")
            IQuietBackgroundProcessesSessionManagerStatics : public IInspectable
            {
            public:
                virtual HRESULT STDMETHODCALLTYPE GetSession(
                    /* [out, retval] */ABI::DevHome::QuietBackgroundProcesses::IQuietBackgroundProcessesSession * * result
                    ) = 0;
                virtual HRESULT STDMETHODCALLTYPE TryGetSession(
                    /* [out, retval] */ABI::DevHome::QuietBackgroundProcesses::IQuietBackgroundProcessesSession * * result
                    ) = 0;
                
            };

            MIDL_CONST_ID IID & IID_IQuietBackgroundProcessesSessionManagerStatics=_uuidof(IQuietBackgroundProcessesSessionManagerStatics);
            
        } /* QuietBackgroundProcesses */
    } /* DevHome */
} /* ABI */

EXTERN_C const IID IID___x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics;
#endif /* !defined(____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_INTERFACE_DEFINED__) */


/*
 *
 * Class DevHome.QuietBackgroundProcesses.QuietBackgroundProcessesSessionManager
 *
 * RuntimeClass can be activated.
 *
 * RuntimeClass contains static methods.
 *
 * Class implements the following interfaces:
 *    DevHome.QuietBackgroundProcesses.IQuietBackgroundProcessesSessionManager ** Default Interface **
 *
 * Class Threading Model:  Both Single and Multi Threaded Apartment
 *
 * Class Marshaling Behavior:  Agile - Class is agile
 *
 */

#ifndef RUNTIMECLASS_DevHome_QuietBackgroundProcesses_QuietBackgroundProcessesSessionManager_DEFINED
#define RUNTIMECLASS_DevHome_QuietBackgroundProcesses_QuietBackgroundProcessesSessionManager_DEFINED
extern const __declspec(selectany) _Null_terminated_ WCHAR RuntimeClass_DevHome_QuietBackgroundProcesses_QuietBackgroundProcessesSessionManager[] = L"DevHome.QuietBackgroundProcesses.QuietBackgroundProcessesSessionManager";
#endif


#else // !defined(__cplusplus)
/* Forward Declarations */
#ifndef ____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_FWD_DEFINED__
#define ____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_FWD_DEFINED__
typedef interface __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager;

#endif // ____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_FWD_DEFINED__

#ifndef ____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_FWD_DEFINED__
#define ____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_FWD_DEFINED__
typedef interface __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics;

#endif // ____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_FWD_DEFINED__



/*
 *
 * Interface DevHome.QuietBackgroundProcesses.IQuietBackgroundProcessesSessionManager
 *
 * Interface is a part of the implementation of type DevHome.QuietBackgroundProcesses.QuietBackgroundProcessesSessionManager
 *
 *
 * The IID for this interface was automatically generated by MIDLRT.
 *
 * Interface IID generation seed: DevHome.QuietBackgroundProcesses.IQuietBackgroundProcessesSessionManager:HRESULT GetInt(Int32*);
 *
 *
 */
#if !defined(____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_INTERFACE_DEFINED__)
#define ____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_INTERFACE_DEFINED__
extern const __declspec(selectany) _Null_terminated_ WCHAR InterfaceName_DevHome_QuietBackgroundProcesses_IQuietBackgroundProcessesSessionManager[] = L"DevHome.QuietBackgroundProcesses.IQuietBackgroundProcessesSessionManager";
/* [uuid("812326e8-ebbc-5b6b-8a72-8840931e547a"), version, object, exclusiveto] */
typedef struct __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerVtbl
{
    BEGIN_INTERFACE
    HRESULT ( STDMETHODCALLTYPE *QueryInterface)(
    __RPC__in __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager * This,
    /* [in] */ __RPC__in REFIID riid,
    /* [annotation][iid_is][out] */
    _COM_Outptr_  void **ppvObject
    );

ULONG ( STDMETHODCALLTYPE *AddRef )(
    __RPC__in __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager * This
    );

ULONG ( STDMETHODCALLTYPE *Release )(
    __RPC__in __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager * This
    );

HRESULT ( STDMETHODCALLTYPE *GetIids )(
    __RPC__in __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager * This,
    /* [out] */ __RPC__out ULONG *iidCount,
    /* [size_is][size_is][out] */ __RPC__deref_out_ecount_full_opt(*iidCount) IID **iids
    );

HRESULT ( STDMETHODCALLTYPE *GetRuntimeClassName )(
    __RPC__in __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager * This,
    /* [out] */ __RPC__deref_out_opt HSTRING *className
    );

HRESULT ( STDMETHODCALLTYPE *GetTrustLevel )(
    __RPC__in __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager * This,
    /* [OUT ] */ __RPC__out TrustLevel *trustLevel
    );
HRESULT ( STDMETHODCALLTYPE *GetInt )(
        __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager * This,
        /* [out, retval] */int * result
        );
    END_INTERFACE
    
} __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerVtbl;

interface __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager
{
    CONST_VTBL struct __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerVtbl *lpVtbl;
};

#ifdef COBJMACROS
#define __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_QueryInterface(This,riid,ppvObject) \
( (This)->lpVtbl->QueryInterface(This,riid,ppvObject) )

#define __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_AddRef(This) \
        ( (This)->lpVtbl->AddRef(This) )

#define __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_Release(This) \
        ( (This)->lpVtbl->Release(This) )

#define __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_GetIids(This,iidCount,iids) \
        ( (This)->lpVtbl->GetIids(This,iidCount,iids) )

#define __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_GetRuntimeClassName(This,className) \
        ( (This)->lpVtbl->GetRuntimeClassName(This,className) )

#define __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_GetTrustLevel(This,trustLevel) \
        ( (This)->lpVtbl->GetTrustLevel(This,trustLevel) )

#define __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_GetInt(This,result) \
    ( (This)->lpVtbl->GetInt(This,result) )


#endif /* COBJMACROS */


EXTERN_C const IID IID___x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager;
#endif /* !defined(____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManager_INTERFACE_DEFINED__) */


/*
 *
 * Interface DevHome.QuietBackgroundProcesses.IQuietBackgroundProcessesSessionManagerStatics
 *
 * Interface is a part of the implementation of type DevHome.QuietBackgroundProcesses.QuietBackgroundProcessesSessionManager
 *
 *
 * The IID for this interface was automatically generated by MIDLRT.
 *
 * Interface IID generation seed: DevHome.QuietBackgroundProcesses.IQuietBackgroundProcessesSessionManagerStatics:HRESULT GetSession(DevHome.QuietBackgroundProcesses.QuietBackgroundProcessesSession**);HRESULT TryGetSession(DevHome.QuietBackgroundProcesses.QuietBackgroundProcessesSession**);
 *
 *
 */
#if !defined(____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_INTERFACE_DEFINED__)
#define ____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_INTERFACE_DEFINED__
extern const __declspec(selectany) _Null_terminated_ WCHAR InterfaceName_DevHome_QuietBackgroundProcesses_IQuietBackgroundProcessesSessionManagerStatics[] = L"DevHome.QuietBackgroundProcesses.IQuietBackgroundProcessesSessionManagerStatics";
/* [uuid("e2335bd1-511c-572e-b204-e35b0878a9c7"), version, object, exclusiveto] */
typedef struct __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStaticsVtbl
{
    BEGIN_INTERFACE
    HRESULT ( STDMETHODCALLTYPE *QueryInterface)(
    __RPC__in __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics * This,
    /* [in] */ __RPC__in REFIID riid,
    /* [annotation][iid_is][out] */
    _COM_Outptr_  void **ppvObject
    );

ULONG ( STDMETHODCALLTYPE *AddRef )(
    __RPC__in __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics * This
    );

ULONG ( STDMETHODCALLTYPE *Release )(
    __RPC__in __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics * This
    );

HRESULT ( STDMETHODCALLTYPE *GetIids )(
    __RPC__in __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics * This,
    /* [out] */ __RPC__out ULONG *iidCount,
    /* [size_is][size_is][out] */ __RPC__deref_out_ecount_full_opt(*iidCount) IID **iids
    );

HRESULT ( STDMETHODCALLTYPE *GetRuntimeClassName )(
    __RPC__in __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics * This,
    /* [out] */ __RPC__deref_out_opt HSTRING *className
    );

HRESULT ( STDMETHODCALLTYPE *GetTrustLevel )(
    __RPC__in __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics * This,
    /* [OUT ] */ __RPC__out TrustLevel *trustLevel
    );
HRESULT ( STDMETHODCALLTYPE *GetSession )(
        __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics * This,
        /* [out, retval] */__x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSession * * result
        );
    HRESULT ( STDMETHODCALLTYPE *TryGetSession )(
        __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics * This,
        /* [out, retval] */__x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSession * * result
        );
    END_INTERFACE
    
} __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStaticsVtbl;

interface __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics
{
    CONST_VTBL struct __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStaticsVtbl *lpVtbl;
};

#ifdef COBJMACROS
#define __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_QueryInterface(This,riid,ppvObject) \
( (This)->lpVtbl->QueryInterface(This,riid,ppvObject) )

#define __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_AddRef(This) \
        ( (This)->lpVtbl->AddRef(This) )

#define __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_Release(This) \
        ( (This)->lpVtbl->Release(This) )

#define __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_GetIids(This,iidCount,iids) \
        ( (This)->lpVtbl->GetIids(This,iidCount,iids) )

#define __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_GetRuntimeClassName(This,className) \
        ( (This)->lpVtbl->GetRuntimeClassName(This,className) )

#define __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_GetTrustLevel(This,trustLevel) \
        ( (This)->lpVtbl->GetTrustLevel(This,trustLevel) )

#define __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_GetSession(This,result) \
    ( (This)->lpVtbl->GetSession(This,result) )

#define __x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_TryGetSession(This,result) \
    ( (This)->lpVtbl->TryGetSession(This,result) )


#endif /* COBJMACROS */


EXTERN_C const IID IID___x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics;
#endif /* !defined(____x_ABI_CDevHome_CQuietBackgroundProcesses_CIQuietBackgroundProcessesSessionManagerStatics_INTERFACE_DEFINED__) */


/*
 *
 * Class DevHome.QuietBackgroundProcesses.QuietBackgroundProcessesSessionManager
 *
 * RuntimeClass can be activated.
 *
 * RuntimeClass contains static methods.
 *
 * Class implements the following interfaces:
 *    DevHome.QuietBackgroundProcesses.IQuietBackgroundProcessesSessionManager ** Default Interface **
 *
 * Class Threading Model:  Both Single and Multi Threaded Apartment
 *
 * Class Marshaling Behavior:  Agile - Class is agile
 *
 */

#ifndef RUNTIMECLASS_DevHome_QuietBackgroundProcesses_QuietBackgroundProcessesSessionManager_DEFINED
#define RUNTIMECLASS_DevHome_QuietBackgroundProcesses_QuietBackgroundProcessesSessionManager_DEFINED
extern const __declspec(selectany) _Null_terminated_ WCHAR RuntimeClass_DevHome_QuietBackgroundProcesses_QuietBackgroundProcessesSessionManager[] = L"DevHome.QuietBackgroundProcesses.QuietBackgroundProcessesSessionManager";
#endif


#endif // defined(__cplusplus)
#pragma pop_macro("MIDL_CONST_ID")
#endif // __DevHome2EQuietBackgroundProcesses2EQuietBackgroundProcessesSessionManager_p_h__

#endif // __DevHome2EQuietBackgroundProcesses2EQuietBackgroundProcessesSessionManager_h__
