namespace QuietBackgroundProcesses_ElevatedServer
{
    [default_interface] runtimeclass QuietWindow
    {
        static Int64 StartQuietWindow();
        static void StopQuietWindow();
        static Boolean IsActive{ get; };
        static Int64 TimeLeftInSeconds{ get; };
    }
}
