namespace QuietBackgroundProcesses_ElevatedServer
{
    [default_interface] runtimeclass QuietBackgroundProcessesManager
    {
        static Int64 StartQuietWindow();
        static void StopQuietWindow();
        static Boolean IsActive{ get; };
        static Int64 TimeLeftInSeconds{ get; };
    }
}
