// Copyright (c) Microsoft Corporation and Contributors
// Licensed under the MIT license.

import "inspectable.idl";
import "DevHome.QuietBackgroundProcesses.QuietBackgroundProcessesSession.idl";

namespace DevHome.QuietBackgroundProcesses
{
    [default_interface]
    runtimeclass QuietBackgroundProcessesSessionManager
    {
        QuietBackgroundProcessesSessionManager();
        static QuietBackgroundProcessesSession GetSession();
        static QuietBackgroundProcessesSession TryGetSession();
        static void InvalidateSessionReference();
    }
}
